/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Converter {
  constructor()
  convert(input: string): string
  addConversion(unit: string, factor: number, offset: number): void
}
